repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=20000"]
      - id: check-yaml
      - id: double-quote-string-fixer

  - repo: https://github.com/prettier/prettier
    rev: 1.18.2
    hooks:
      - id: prettier
  
  -   repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
      - id: black
  
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      - id: flake8